### ISSUE TITLE
Sinan hooks problem

### ISSUE THREAD

**Issue by ericbmerritt** [erlware-deprecated/sinan#48]
I've attempted to use the new sinan with a project with a hook in it and it seems to blow everything up:

starting: depends
build problem error:badarg:[{erlang,open_port,
[{spawn,
"/home/tristan/Devel/claimstrade/_hooks/pre_build"},

I'm not positive its due to the hook but I'm also trying to build another project on this same system without a hook that gave me a different error.

I sent the other projects error in my email to the sinan alpha thread.

@tsloughter

**Comment by ericbmerritt** [comment]
@tsloughter please verify that this is fixed in the latest and greatest

**Comment by tsloughter** [comment]
Still fails:

build problem sin_hooks:123 [{bad_exit_status,[72,111,111,107,32,"pre_build",32,101,120,105,
                                 116,101,100,32,119,105,116,104,32,115,116,97,
                                 116,117,115,32,"1"]}]

**Comment by ericbmerritt** [comment]
which project?

**Comment by tsloughter** [comment]
ClaimsTrade

**Comment by tsloughter** [comment]
Newest release works! Thanks
